Components/SidebarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RoomForRent.Components
{
    public class SideBarViewData
    {
        public Dictionary<string, ActionAndDisplayName> Data
        { get; internal set; } = new Dictionary<string, ActionAndDisplayName>();

        public void AddViewData(string controllerName, string actionName, string displayName)
        {
            this.Data.Add(controllerName, new SideBarViewData.ActionAndDisplayName
            {
                ActionName = actionName,
                DisplayName = displayName,
            });
        }

        internal void SetActiveController(string controllerName)
        {
            if (this.Data.ContainsKey(controllerName) == false)
                this.Data.Add(controllerName, new ActionAndDisplayName
                {
                    ActionName = "Index",
                    DisplayName = controllerName
                });
            this.Data[controllerName].IsSelected = true;
        }

        public IEnumerable<(string controllerName,string actioName ,string displayName,bool isSelected)> GetItems()
        {
            foreach(var key in this.Data.Keys)
            {
                yield return (key, this.Data[key].ActionName, this.Data[key].DisplayName, this.Data[key].IsSelected);
            }
        }
        
        public class ActionAndDisplayName
        {
            public string ActionName { get; set; }
            public string DisplayName { get; set; }
            public bool IsSelected { get; set; }
        }
    }

    public class SidebarViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var currentController = this.RouteData?.Values["controller"]?.ToString() ?? "Home";

            var viewData = BuildViewData();
            viewData.SetActiveController(currentController);
            return View(viewData);
        }

        private SideBarViewData BuildViewData()
        {
            var sideBarData = new SideBarViewData();

            sideBarData.AddViewData("Home", "Index", "Transactions");
            sideBarData.AddViewData("Renter", "Index", "Renters");
            sideBarData.AddViewData("Leaser", "Index", "Leasers");
            
            return sideBarData;
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Room for Rent</title>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/lib/twitter-bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/styles.css" />
    <script type="text/javascript" src="~/scripts/jquery/jquery.min.js" >
    </script>
    <script type="text/javascript" src="~/scripts/RoomForRent.js"></script>
</head>
<body>
    <div class="bg-dark text-white text-center">
        <span class="navbar-brand ml-2">Welcome to RoomForRent</span>
        <partial name="_UserLoginInfo" />
    </div>
    <div class="container-fluid">
        <div class="row m-2">
            <div class="col-2">
                <vc:sidebar />
            </div>
            <div class="col-10">
                @RenderBody()
            </div>
            @*<div class="col-2">
                    <div class=""
                        Side Bar Content
                    <div>
                </div>*@
        </div>
    </div>

    @RenderSection("Footer", required: false);
    @if (!IsSectionDefined("Footer"))
    {
        <style>
            .footer {
                position: fixed;
                left: 0;
                bottom: 0;
                width: 100%;
            }
        </style>
        <footer class="footer">
            <div class="bg-dark text-white text-center ">
                <span>CopyRight RoomForRent©2020 </span>
            </div>
        </footer>
    }
</body>
</html>

Views/Shared/_UserLoginInfo.cshtml
@{
    var path = ViewContext.HttpContext.Request.Path;

    var identity = ViewContext.HttpContext.User.Identity;

    var loggedIn = identity.IsAuthenticated;

    if (loggedIn)
    {
        <span class="text-right">Hello, @identity.Name</span>
    }

    var placeHolder = loggedIn == false ? "Login" : "Logout";
    <a asp-action="@(placeHolder)" asp-controller="Account" asp-route-returnUrl="@path" class="m-1 btn btn-sm btn-light">@placeHolder</a>
}