Models/Renter/Renter.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace RoomForRent.Models
{
    public class Renter
    {
        public long ID { get; set; }

        [Required(ErrorMessage = "Name should be entered.")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Address should be entered.")]
        public string Address { get; set; }

        [Required(ErrorMessage = "Contact Number should be entered.")]
        public string ContactNumber { get; set; }

        [Required(ErrorMessage = "Seeked Asset should be entered.")]
        public AssetType SeekedAsset { get; set; }

        public bool? Found { get; set; }

        public DateTime? FoundDate { get; set; }

        [Required(ErrorMessage = "Description should be entered.")]
        public string Description { get; set; }
    }
}

Models/Renter/RenterCreateModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace RoomForRent.Models
{
    public class RenterCreateModel
    {
        [Required(ErrorMessage = "Name should be entered.")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Address should be entered.")]
        public string Address { get; set; }

        [Required(ErrorMessage = "Contact Number should be entered.")]
        public string ContactNumber { get; set; }

        [Required(ErrorMessage = "Seeked Asset should be entered.")]
        public AssetType SeekedAsset { get; set; }

        [Required(ErrorMessage = "Description should be entered.")]
        public string Description { get; set; }
    }
}

Models/Renter/RenterEditModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace RoomForRent.Models
{
    public class RenterEditModel
    {
        public long ID { get; set; }

        [Required(ErrorMessage = "Name should be entered.")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Address should be entered.")]
        public string Address { get; set; }

        [Required(ErrorMessage = "Contact Number should be entered.")]
        public string ContactNumber { get; set; }

        [Required(ErrorMessage = "Seeked Asset should be entered.")]
        public AssetType SeekedAsset { get; set; }

        [Required(ErrorMessage = "Description should be entered.")]
        public string Description { get; set; }
    }
}

Components/ActiveTransactionsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using RoomForRent.Controllers;
using RoomForRent.Repositories;
using RoomForRent.Services.RenterLeaserTransactionServiceProvider;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RoomForRent.Components
{
    public class ActiveTransactionsViewComponent : ViewComponent
    {
        private RenterLeaserTransactionService service = null;

        public ActiveTransactionsViewComponent(IRepositoryWrapper repositoryWrapper)
        {
            service = new RenterLeaserTransactionService(repositoryWrapper);
        }

        public IViewComponentResult Invoke(int id, bool isRenter)
        {
            //var x = this.RouteData?.Values["id"] ?? string.Empty;

            //if (!int.TryParse(x.ToString(), out int renterId))
            //{
            //    renterId = 0;
            //}

            //int id = renterId;
                
            //    bool isRenter = true;

            var transactionViewDto = new TransactionViewDto
            {
                ShowAssociatedLeasers = isRenter,
            };

            if(isRenter)
                transactionViewDto.TransactionDtos = service.GetAllRenterTransactions(id);
            else
                transactionViewDto.TransactionDtos = service.GetAllLeaserTransactions(id);
            
            return View(transactionViewDto);
        }
    }

    public class TransactionViewDto
    {
        public bool ShowAssociatedLeasers { get; set; }
        public IEnumerable<RenterLeaserTransactionDto> TransactionDtos { get; set; }
    }
}

Controllers/RenterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using RoomForRent.Infrastructure;
using RoomForRent.Models;
using RoomForRent.Models.ViewModel;
using RoomForRent.Repositories;
using RoomForRent.Services.RenterLeaserTransactionServiceProvider;
using RoomForRent.Services.RenterServiceProvider;

namespace RoomForRent.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RenterController : Controller
    {
        private readonly IOptions<RoomForRentOptions> optionsAccessor;

        private readonly IRenterRepository renterRepository;

        private readonly RenterService renterService = null;

        private readonly RenterLeaserTransactionService transactionService = null;

        private readonly IRepositoryWrapper repositoryWrapper = null;

        public RenterController(IOptions<RoomForRentOptions> optionsAccessor, IRepositoryWrapper repositoryWrapper)
        {
            this.repositoryWrapper = repositoryWrapper;
            this.optionsAccessor = optionsAccessor;
            this.ItemsPerPage = optionsAccessor.Value.ItemsPerPage;

            this.renterRepository = repositoryWrapper.RenterRepository;
            renterService = new RenterService(renterRepository);

            this.transactionService = new RenterLeaserTransactionService(repositoryWrapper);
        }

        private readonly int ItemsPerPage;

        public async Task<IActionResult> Index(int pageCount,string renterName=null)
        {
            if (pageCount <= 1)
                pageCount = 1;

            if(string.IsNullOrWhiteSpace(renterName) == false)
            {
                var renters = await this.renterRepository
                                .GetRentersByName(renterName, pageCount, this.ItemsPerPage);

                var renterViewInfo = new RenterListViewModel
                {
                    CurrentRenter = renterName,
                    Renters = renters,
                    PagingInfo = new PagingInfo
                    {
                        CurrentPage = pageCount,
                        ItemsPerPage = this.ItemsPerPage,
                        TotalItems = await this.renterRepository.GetRentersByNameCount(renterName,false)
                    }
                };
                return View(renterViewInfo);
            } 
            else
            {
                var renterViewInfo = await renterService
                    .GetRenterList(pageCount, ItemsPerPage);
                return View(renterViewInfo);
            }
        }

        public async Task<IActionResult> History()
        {
            var pastRenters = await renterService.GetHistory();

            return View(pastRenters);
        }

        [HttpPost]
        public async Task<IActionResult> MarkAsFound(int renterId)
        {
            var success = await renterService.MarkAsFound(renterId);
            if (success)
                return RedirectToAction("Index");
            else
                return BadRequest();
        }

        public async Task<IActionResult> Details([FromRoute(Name ="id")] int renterId)
        {
            var renter = await renterService.GetRenterDetails(renterId);
            return View(renter);
        }

        // custom attributed created for implementing
        // POST-REDIRECT-GET pattern
        [ImportModelState]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        // custom attribute created for implementing
        // POST-REDIRECT-GET pattern
        [ExportModelState]
        public async Task<IActionResult> Create(RenterCreateModel renterCreateModel)
        {
            if(this.ModelState.IsValid)
            {
                var result = await renterService.CreateRenter(renterCreateModel);

                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Create");
            }
        }

        [ImportModelState]
        public async Task<IActionResult> EditDetails([FromRoute(Name = "id")] int renterId)
        {
            var renterEditModel = await renterService.GetRenterEditDetails(renterId);

            if(renterEditModel != null)
                return View(renterEditModel);
            else
                return NotFound();
        }

        [HttpPost]
        [ExportModelState]
        public async Task<IActionResult> EditDetails(RenterEditModel renterEditModel)
        {
            if (ModelState.IsValid)
            {
                var result = await renterService.EditRenterDetails(renterEditModel);

                if (result == true)
                    return RedirectToAction("Index");
                else
                    return BadRequest();
            }

            return RedirectToAction("EditDetails", new { id = renterEditModel.ID });
        }

        [HttpPost]
        public JsonResult CancelRent([FromForm] int renterId)
        {
            var result = this.transactionService.CancelRenterTransaction(renterId);
            return new JsonResult(new { RenterId = renterId, IsSuccess = result });
        }
    }
}

Views/Renter/Create.cshtml
@model Renter
<div class="bg-dark text-white text-center m-2 p-2">
    <span class="navbar-brand">Enter New Renter Details:</span>
</div>
<div class="container">
    <div asp-validation-summary="All"></div>
    <form asp-action="Create" method="post">
        <div class="form-group">
            <label asp-for="Name">Name: </label>
            <input asp-for="Name" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Address">Address: </label>
            <input asp-for="Address" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="ContactNumber">Contact: </label>
            <input asp-for="ContactNumber" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Description"></label>
            <input asp-for="Description" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="SeekedAsset">Seeked Asset: </label>
            <select asp-for="SeekedAsset" class="form-control">
                @foreach (var asset in Enum.GetNames(typeof(AssetType)))
                {
                    <option value="@asset">@asset</option>
                }
            </select>
        </div>
        <button type="submit" class="btn btn-dark">Submit</button>
    </form>
</div>

Views/Renter/Details.cshtml
@model Renter
@if (Model == null)
{
    <div>No information available</div>
}
else
{
<div class="container">
    <h3>Renter Details: </h3>
    <table class="table table-sm table-striped table-bordered">
        <tr>
            <td>Name: @Model.Name</td>
        </tr>
        <tr>
            <td>Address: @Model.Address</td>
        </tr>
        <tr>
            <td>Contact : @Model.ContactNumber</td>
        </tr>
        <tr>
            <td>Seeking Asset: @Model.SeekedAsset.ToString()</td>
        </tr>
        <tr>
            <td>Description: @Model.Description</td>
        </tr>
        @if (Model.Found.HasValue && Model.Found.Value == true) {
        <tr>
            <td>
                Rent Status:  Rented at @(Model.FoundDate.HasValue
                    ? Model.FoundDate.Value.ToShortDateString() : "N/A" )
            </td>
        </tr>
        }
        <tr>
            <td>
                <vc:active-transactions id="@((int)Model.ID)" is-renter="true" />
            </td>
        </tr>
    </table>
</div>
}

Views/Renter/EditDetails.cshtml
@model RenterEditModel

@if(Model == null)
{
    <h2>No information available.</h2>
} else
{
    <h2>Edit Renter Details:</h2>
    <div asp-validation-summary="All">
    </div>
    <form asp-action="EditDetails" method="post">
        <div class="form-group">
            <label asp-for="Name">Name: </label>
            <input asp-for="Name" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Address">Address: </label>
            <input asp-for="Address" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="ContactNumber">Contact Number: </label>
            <input asp-for="ContactNumber" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Description">Description: </label>
            <input asp-for="Description" class="form-control" />
        </div>
        <div class="form-group">
            <label>Asset Type</label>
            <select asp-for="SeekedAsset" class="form-control">
                @foreach (var assetType in Enum.GetValues(typeof(AssetType)))
                {
                    if (assetType == @Model.SeekedAsset.ToString())
                    {
                        <option value="@assetType" selected>@assetType</option>
                    }
                    else
                    {
                        <option value="@assetType" >@assetType</option>
                    }
                }
            </select>
        </div>
        <button type="submit" class="btn btn-dark">Update</button>
    </form>
}

Views/Renter/History.cshtml
@model IEnumerable<Renter>
    <div class="bg-dark text-white text-center p-2">
        <span class="navbar-brand text-center">Past Renters</span>
        <a class="btn btn-light float-right" asp-action="Index">Active Renters</a>
    </div>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Address</th>
            <th>Contact</th>
            <th>Seeked Asset</th>
            <th>Details</th>
            <th>Found Date</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var renter in Model)
        {
            <tr>
                <td>@renter.Name</td>
                <td>@renter.Address</td>
                <td>@renter.ContactNumber</td>
                <td>@renter.SeekedAsset.ToString()</td>
                <td>
                    <a asp-action="Details" asp-route-id="@renter.ID">View Details</a>
                </td>
                <td>
                    @(renter.FoundDate.HasValue ? renter.FoundDate.Value.ToShortDateString(): 
                    "N/A")
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Renter/Index.cshtml
@model RenterListViewModel

<nav class="nav navbar-dark bg-dark" >
    <span class="navbar-brand text-center ml-2">Active Renters</span>
    <ul class="nav ml-auto p-2">
        <li class="nav-item">
            <form method = "get" asp-action="Index" class="form-inline ml-2">
                <input type="text" placeholder="Search Renter" name="renterName" id="renterName"
                        autocomplete="off"
                        required
                        onkeydown="if (event.keyCode == 13)
                document.getElementById('btnSearch').click()" />
                <input type="submit" value="Search" id="btnSearch" style="visibility:hidden;width:0px" />
            </form>
        </li>
        <li class="nav-item">
            <a class="btn btn-light ml-2 p-1" asp-action="Create">Add Renter</a>
        </li>
        <li class="nav-item">
            <a class="btn btn-light ml-2 p-1" asp-action="History">History</a>
        </li>

    </ul>
</nav>

<div class="container-fluid">
    <div class="row">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Address</th>
                    <th>Contact</th>
                    <th>Seeked Asset</th>
                    <th>Details</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                
                @foreach (var renter in Model.Renters)
                {
                    <tr id="rid_@renter.ID">
                        <td>@renter.Name</td>
                        <td>@renter.Address</td>
                        <td>@renter.ContactNumber</td>
                        <td>@renter.SeekedAsset.ToString()</td>
                        <td>
                            <a class="btn-sm btn-dark" asp-action="Details" asp-route-id="@renter.ID">View Details</a>
                            <a class="btn-sm btn-dark m-1" asp-action="EditDetails" asp-route-id="@renter.ID" >Edit</a>
                            <a class="btn-sm btn-dark m-1" asp-action="LinkToLeaser" asp-controller="Home" asp-route-id="@renter.ID">Link</a>
                        </td>
                        <td>
                            <form>
                                <input type="hidden" name="renterId" value="@renter.ID" />
                                <button class="btn btn-sm btn-danger" type="submit" onclick="return function (event) {
                                    event.preventDefault();
                                    let rowId = 'rid_@renter.ID';
                                    let dataToSend = { renterId: @renter.ID }
                                    let url = '@Url.Action("CancelRent")';
                                    postDataToUrlAndHideElementOnSuccess(rowId,dataToSend,url);
                                }(event)">Cancel Rent</button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    @if (Model.Renters.Count() > 0)
    {
        <div class="row">
            <div page-model="@Model.PagingInfo" page-action="Index"
                 page-classes-enabled="true"
                 page-class="btn" page-class-normal="btn-outline-dark"
                 page-class-selected="btn-dark"
                 page-url-renterName="Model.CurrentRenter"
                 class="btn-group pull-right m-1">
            </div>
        </div>
    }
</div>